# # Use Node base image
# FROM node:20

# # Set working directory
# WORKDIR /app

# # Copy package files first
# COPY package*.json ./

# # Install dependencies
# RUN npm install

# # Copy remaining project files
# COPY . .

# # Build the project (compile TS to JS)
# RUN npm run build

# # Expose port (adjust if needed)
# EXPOSE 3000

# # Start the app
# CMD ["npm", "start"]
