name: Push Updated Docker Image

on:
  push:
    branches:
      - add_or_update_donorlist-SravyaPadala-240227

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 21.6.1

    - name: Install dependencies
      run: npm install

    - name: Code linting
      run: npx eslint .

    - name: Code Testing
      run: npm run test
