name: CI/CD Pipeline
#//Docker
on:
  push:
    branches:
      - Code-Linting-Workflow-alar12-02-07-2024

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Docker
        run: docker --version

      - name: Build Docker image
        run: |
          cd crew_manual
          docker build -t alar12/my-app .

      - name: Log in to Docker Hub
        run: docker login -u alar12 -p Aa12345*#

      - name: Push Docker image
        run: docker push alar12/my-app

      - name: Install ESLint globally
        run: npm install -g eslint

      - name: Run linter
        run: npm run lint
      
      - name: Run ESLint
        run: npx eslint .