name: CI/CD Pipeline

on:
  push:
    branches:
      - Code-Linting-Workflow-Vineeth0502-02-07-2024


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        run: docker --version
      
      - name: Build Docker image
        run: |
          cd crew_manual
          docker build -t vineeth173/my-astro-app .

      - name: Log in to Docker Hub
        run: docker login -u vineeth173 -p Vineeth@05

      - name: Push Docker image
        run: docker push vineeth173/my-astro-app
      
      - name: Run Docker container
        run: docker run -d -p 4321:3000 vineeth173/my-astro-app


  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Lint Code Base
          uses: actions/checkout@v2
          env:
            VALIDATE_ALL_CODEBASE: false
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      