name: CI/CD Pipeline

on:
  push:
    branches:
      - Code-Linting-Workflow-VenkataSaiPolakam-240207
      - main
  pull_request:
    branches:
      - Code-Linting-Workflow-VenkataSaiPolakam-240207
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    # - name: Run ESLint
    #   run: npm run lint